name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"
  S3_BUCKET: "ml-models-bucket-eto1"
  SAGEMAKER_ROLE: "arn:aws:iam::825765427114:role/service-role/AmazonSageMaker-ExecutionRole-20250210T121816"

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install boto3 pandas scikit-learn sagemaker

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Generate Dataset
        run: python generate_data.py

      - name: Preprocess Data
        run: python preprocess.py  # ✅ Ensures `X_train.csv` exists

      - name: Check if Dataset Exists
        run: ls -lah  # ✅ Debugging step to check if `X_train.csv` exists

      - name: Run Training
        run: python train.py

  deploy:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Deploy Model
        run: python deploy.py
